import type { Metadata } from "next";
import "../../globals.css";
import localFont from "next/font/local";

// Fonts
import { Cal_Sans, Montserrat } from "next/font/google";

const amoria = localFont({
  src: "../../../public/fonts/AMORIA.otf",
  variable: "--font-amoria",
  display: "swap",
});

const calSans = Cal_Sans({
  variable: "--font-cal-sans",
  subsets: ["latin"],
  weight: "400",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

// Metadata
export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${calSans.variable} ${montserrat.variable} ${amoria.variable} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
