export {
    type SkillItem,
    type OrganizationItem,
    type SocialItem,
    type ServiceItem,
    type WorkItem,
    type ExperienceItem,
    featuredTechStacks,
    languages,
    frameworksAndLibraries,
    tools,
    organizations,
    experiences,
    services,
    works,
    socials,
} from "./portfolioData";
